name: Test ARM Runner

on: workflow_dispatch

jobs:
  check-arm-capability:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check Architecture
        run: |
          echo "Running on architecture:"
          uname -m
          lscpu
